version: '3.8'
services:
  api:
    build: .
    container_name: iot_rpa_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
